-- use <C-j>
-- https://github.com/zbirenbaum/copilot.lua#setup-and-configuration
-- MOVED SETUP into packer.lua, I know not healthy, but it works I guess
-- require('copilot').setup {
--     suggestion = {
--         auto_trigger = true,
--         keymap = {
--             accept = '<C-j>',
--         }
--     }
-- }
