-- vim.api.nvim_create_autocmd({
--   pattern = { '*' },
--   callback = function()
--     -- Only start treesitter if a valid parser is installed for the file type
--     local lang = vim.treesitter.language.get_lang(vim.bo.filetype)
--     if lang and pcall(vim.treesitter.start) then
--       -- Treesitter successfully started
--     else
--       vim.cmd('syntax on') -- Fallback to legacy regex syntax
--     end
--   end,
-- }, 'FileType')
--
-- -- Set up treesitter-based indentation using the rewritten plugin API:
-- vim.api.nvim_create_autocmd('FileType', {
--   pattern = { '*' },
--   callback = function()
--     vim.bo.indentexpr = "v:lua.require'nvim-treesitter'.indentexpr()"
--   end,
-- })
